apiVersion: operator.gatekeeper.sh/v1alpha1
kind: Gatekeeper
metadata:
  name: gatekeeper
spec:
  audit:
    replicas: 1
    logLevel: INFO
    auditInterval: "30"
    auditChunkSize: 500
    constraintViolationsLimit: 5
    auditFromCache: Enabled
    auditMatchKindOnly: true
  validatingWebhook: Enabled
  webhook:
    logLevel: INFO
    replicas: 2
  image:
    image: >-
      registry.redhat.io/rhacm2/gatekeeper-rhel8@sha256:5e66cd510a80ef5753c66c6b50137de0093fe75c0606f5f8ce4afce7d7bca050    
